sudo: required
services: docker
script:
  - docker build -t fifths/nginx:1.16.1 ./1.16/1.16.1/alpine3.10/
  - docker build -t fifths/nginx:1.17.6 ./1.17/1.17.6/alpine3.10/
after_script:
  - docker images
